# Generated by Django 4.2 on 2023-04-26 00:08

import core.users.managers
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField()),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(db_collation='und-x-icu', max_length=254, unique=True, verbose_name='email')),
                ('address', models.CharField(blank=True, max_length=255)),
                ('zip_code', models.CharField(blank=True, max_length=16)),
                ('state', models.CharField(blank=True, max_length=128)),
                ('city', models.CharField(blank=True, max_length=128)),
                ('is_designer', models.BooleanField(default=False)),
                ('is_reviewer', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['email', '-created_at'],
            },
            managers=[
                ('objects', core.users.managers.UserManager()),
            ],
        ),
    ]
